//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.17929
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nsun.Workflow.SerContainer.WFService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entity", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Samples.NLayerApp.Domain.Seedwo" +
        "rk")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Nsun.Workflow.SerContainer.WFService.NSTemplateType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Nsun.Workflow.SerContainer.WFService.NSInstanceInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Nsun.Workflow.SerContainer.WFService.NSNodeInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Nsun.Workflow.SerContainer.WFService.NSRoutingData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Nsun.Workflow.SerContainer.WFService.NSTemplateInfo))]
    public partial class Entity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NSTemplateType", Namespace="http://schemas.datacontract.org/2004/07/Nsun.Domain.MainBoundedContext.WorkflowMo" +
        "dule.Aggregates.WorkflowAgg")]
    [System.SerializableAttribute()]
    public partial class NSTemplateType : Nsun.Workflow.SerContainer.WFService.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateDesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateDes {
            get {
                return this.TemplateDesField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateDesField, value) != true)) {
                    this.TemplateDesField = value;
                    this.RaisePropertyChanged("TemplateDes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateType {
            get {
                return this.TemplateTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateTypeField, value) != true)) {
                    this.TemplateTypeField = value;
                    this.RaisePropertyChanged("TemplateType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NSInstanceInfo", Namespace="http://schemas.datacontract.org/2004/07/Nsun.Domain.MainBoundedContext.WorkflowMo" +
        "dule.Aggregates.WorkflowAgg")]
    [System.SerializableAttribute()]
    public partial class NSInstanceInfo : Nsun.Workflow.SerContainer.WFService.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstanceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ParentNodeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RunStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid TaskIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid TemplateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstanceName {
            get {
                return this.InstanceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.InstanceNameField, value) != true)) {
                    this.InstanceNameField = value;
                    this.RaisePropertyChanged("InstanceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentNodeId {
            get {
                return this.ParentNodeIdField;
            }
            set {
                if ((this.ParentNodeIdField.Equals(value) != true)) {
                    this.ParentNodeIdField = value;
                    this.RaisePropertyChanged("ParentNodeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RunState {
            get {
                return this.RunStateField;
            }
            set {
                if ((object.ReferenceEquals(this.RunStateField, value) != true)) {
                    this.RunStateField = value;
                    this.RaisePropertyChanged("RunState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TaskId {
            get {
                return this.TaskIdField;
            }
            set {
                if ((this.TaskIdField.Equals(value) != true)) {
                    this.TaskIdField = value;
                    this.RaisePropertyChanged("TaskId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TemplateId {
            get {
                return this.TemplateIdField;
            }
            set {
                if ((this.TemplateIdField.Equals(value) != true)) {
                    this.TemplateIdField = value;
                    this.RaisePropertyChanged("TemplateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateName {
            get {
                return this.TemplateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateNameField, value) != true)) {
                    this.TemplateNameField = value;
                    this.RaisePropertyChanged("TemplateName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NSNodeInfo", Namespace="http://schemas.datacontract.org/2004/07/Nsun.Domain.MainBoundedContext.WorkflowMo" +
        "dule.Aggregates.WorkflowAgg")]
    [System.SerializableAttribute()]
    public partial class NSNodeInfo : Nsun.Workflow.SerContainer.WFService.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid InstanceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NodeDesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid NodeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NodeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RunStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubmitOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubmitResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SubmitTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubmitUserNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid TaskIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransUserNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid InstanceId {
            get {
                return this.InstanceIdField;
            }
            set {
                if ((this.InstanceIdField.Equals(value) != true)) {
                    this.InstanceIdField = value;
                    this.RaisePropertyChanged("InstanceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NodeDes {
            get {
                return this.NodeDesField;
            }
            set {
                if ((object.ReferenceEquals(this.NodeDesField, value) != true)) {
                    this.NodeDesField = value;
                    this.RaisePropertyChanged("NodeDes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid NodeId {
            get {
                return this.NodeIdField;
            }
            set {
                if ((this.NodeIdField.Equals(value) != true)) {
                    this.NodeIdField = value;
                    this.RaisePropertyChanged("NodeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NodeName {
            get {
                return this.NodeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NodeNameField, value) != true)) {
                    this.NodeNameField = value;
                    this.RaisePropertyChanged("NodeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RunState {
            get {
                return this.RunStateField;
            }
            set {
                if ((object.ReferenceEquals(this.RunStateField, value) != true)) {
                    this.RunStateField = value;
                    this.RaisePropertyChanged("RunState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmitOptions {
            get {
                return this.SubmitOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmitOptionsField, value) != true)) {
                    this.SubmitOptionsField = value;
                    this.RaisePropertyChanged("SubmitOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmitResult {
            get {
                return this.SubmitResultField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmitResultField, value) != true)) {
                    this.SubmitResultField = value;
                    this.RaisePropertyChanged("SubmitResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SubmitTime {
            get {
                return this.SubmitTimeField;
            }
            set {
                if ((this.SubmitTimeField.Equals(value) != true)) {
                    this.SubmitTimeField = value;
                    this.RaisePropertyChanged("SubmitTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmitUserNo {
            get {
                return this.SubmitUserNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmitUserNoField, value) != true)) {
                    this.SubmitUserNoField = value;
                    this.RaisePropertyChanged("SubmitUserNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TaskId {
            get {
                return this.TaskIdField;
            }
            set {
                if ((this.TaskIdField.Equals(value) != true)) {
                    this.TaskIdField = value;
                    this.RaisePropertyChanged("TaskId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransUserNo {
            get {
                return this.TransUserNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TransUserNoField, value) != true)) {
                    this.TransUserNoField = value;
                    this.RaisePropertyChanged("TransUserNo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NSRoutingData", Namespace="http://schemas.datacontract.org/2004/07/Nsun.Domain.MainBoundedContext.WorkflowMo" +
        "dule.Aggregates.WorkflowAgg")]
    [System.SerializableAttribute()]
    public partial class NSRoutingData : Nsun.Workflow.SerContainer.WFService.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid InstanceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransOutField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid InstanceId {
            get {
                return this.InstanceIdField;
            }
            set {
                if ((this.InstanceIdField.Equals(value) != true)) {
                    this.InstanceIdField = value;
                    this.RaisePropertyChanged("InstanceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransData {
            get {
                return this.TransDataField;
            }
            set {
                if ((object.ReferenceEquals(this.TransDataField, value) != true)) {
                    this.TransDataField = value;
                    this.RaisePropertyChanged("TransData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransIn {
            get {
                return this.TransInField;
            }
            set {
                if ((object.ReferenceEquals(this.TransInField, value) != true)) {
                    this.TransInField = value;
                    this.RaisePropertyChanged("TransIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransOut {
            get {
                return this.TransOutField;
            }
            set {
                if ((object.ReferenceEquals(this.TransOutField, value) != true)) {
                    this.TransOutField = value;
                    this.RaisePropertyChanged("TransOut");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NSTemplateInfo", Namespace="http://schemas.datacontract.org/2004/07/Nsun.Domain.MainBoundedContext.WorkflowMo" +
        "dule.Aggregates.WorkflowAgg")]
    [System.SerializableAttribute()]
    public partial class NSTemplateInfo : Nsun.Workflow.SerContainer.WFService.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateName {
            get {
                return this.TemplateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateNameField, value) != true)) {
                    this.TemplateNameField = value;
                    this.RaisePropertyChanged("TemplateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateText {
            get {
                return this.TemplateTextField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateTextField, value) != true)) {
                    this.TemplateTextField = value;
                    this.RaisePropertyChanged("TemplateText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateType {
            get {
                return this.TemplateTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateTypeField, value) != true)) {
                    this.TemplateTypeField = value;
                    this.RaisePropertyChanged("TemplateType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StartInfo_DTO", Namespace="http://schemas.datacontract.org/2004/07/Nsun.Workflow.Common.DTOs")]
    [System.SerializableAttribute()]
    public partial class StartInfo_DTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid TemplateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskName {
            get {
                return this.TaskNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskNameField, value) != true)) {
                    this.TaskNameField = value;
                    this.RaisePropertyChanged("TaskName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskType {
            get {
                return this.TaskTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskTypeField, value) != true)) {
                    this.TaskTypeField = value;
                    this.RaisePropertyChanged("TaskType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TemplateId {
            get {
                return this.TemplateIdField;
            }
            set {
                if ((this.TemplateIdField.Equals(value) != true)) {
                    this.TemplateIdField = value;
                    this.RaisePropertyChanged("TemplateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateName {
            get {
                return this.TemplateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateNameField, value) != true)) {
                    this.TemplateNameField = value;
                    this.RaisePropertyChanged("TemplateName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmitInfo_DTO", Namespace="http://schemas.datacontract.org/2004/07/Nsun.Workflow.Common.DTOs")]
    [System.SerializableAttribute()]
    public partial class SubmitInfo_DTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Nsun.Workflow.SerContainer.WFService.ExpandData> ExpandDatasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid NodeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubmitResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Condition {
            get {
                return this.ConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConditionField, value) != true)) {
                    this.ConditionField = value;
                    this.RaisePropertyChanged("Condition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Nsun.Workflow.SerContainer.WFService.ExpandData> ExpandDatas {
            get {
                return this.ExpandDatasField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpandDatasField, value) != true)) {
                    this.ExpandDatasField = value;
                    this.RaisePropertyChanged("ExpandDatas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid NodeId {
            get {
                return this.NodeIdField;
            }
            set {
                if ((this.NodeIdField.Equals(value) != true)) {
                    this.NodeIdField = value;
                    this.RaisePropertyChanged("NodeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmitResult {
            get {
                return this.SubmitResultField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmitResultField, value) != true)) {
                    this.SubmitResultField = value;
                    this.RaisePropertyChanged("SubmitResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpandData", Namespace="http://schemas.datacontract.org/2004/07/Nsun.Workflow.Common.DTOs")]
    [System.SerializableAttribute()]
    public partial class ExpandData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CounterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ExpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Counter {
            get {
                return this.CounterField;
            }
            set {
                if ((this.CounterField.Equals(value) != true)) {
                    this.CounterField = value;
                    this.RaisePropertyChanged("Counter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Exp {
            get {
                return this.ExpField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpField, value) != true)) {
                    this.ExpField = value;
                    this.RaisePropertyChanged("Exp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstanceNode_DTO", Namespace="http://schemas.datacontract.org/2004/07/Nsun.Workflow.Common.DTOs")]
    [System.SerializableAttribute()]
    public partial class InstanceNode_DTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WFService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NewTemplate", ReplyAction="http://tempuri.org/IService1/NewTemplateResponse")]
        string NewTemplate(Nsun.Workflow.SerContainer.WFService.NSTemplateInfo nsTemplateInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NewTemplateType", ReplyAction="http://tempuri.org/IService1/NewTemplateTypeResponse")]
        string NewTemplateType(Nsun.Workflow.SerContainer.WFService.NSTemplateType nsTemplateInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelTemplateTypes", ReplyAction="http://tempuri.org/IService1/DelTemplateTypesResponse")]
        string DelTemplateTypes(System.Collections.Generic.List<Nsun.Workflow.SerContainer.WFService.NSTemplateType> delItems);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NewTemplateTypes", ReplyAction="http://tempuri.org/IService1/NewTemplateTypesResponse")]
        string NewTemplateTypes(System.Collections.Generic.List<Nsun.Workflow.SerContainer.WFService.NSTemplateType> nsTemplateInfos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTemplateType", ReplyAction="http://tempuri.org/IService1/GetAllTemplateTypeResponse")]
        System.Collections.Generic.List<Nsun.Workflow.SerContainer.WFService.NSTemplateType> GetAllTemplateType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTemplateInfoByType", ReplyAction="http://tempuri.org/IService1/GetAllTemplateInfoByTypeResponse")]
        System.Collections.Generic.List<Nsun.Workflow.SerContainer.WFService.NSTemplateInfo> GetAllTemplateInfoByType(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/StartWorkflowInfo", ReplyAction="http://tempuri.org/IService1/StartWorkflowInfoResponse")]
        System.Guid StartWorkflowInfo(Nsun.Workflow.SerContainer.WFService.StartInfo_DTO startInfo, ref string errorInfos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNSInfoInfosByTaskId", ReplyAction="http://tempuri.org/IService1/GetNSInfoInfosByTaskIdResponse")]
        System.Collections.Generic.List<Nsun.Workflow.SerContainer.WFService.NSInstanceInfo> GetNSInfoInfosByTaskId(System.Guid taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNSNodeInfosByInstanceId", ReplyAction="http://tempuri.org/IService1/GetNSNodeInfosByInstanceIdResponse")]
        System.Collections.Generic.List<Nsun.Workflow.SerContainer.WFService.NSNodeInfo> GetNSNodeInfosByInstanceId(System.Guid instanceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNSRouingData", ReplyAction="http://tempuri.org/IService1/GetNSRouingDataResponse")]
        System.Collections.Generic.List<Nsun.Workflow.SerContainer.WFService.NSRoutingData> GetNSRouingData(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SubmitWorkflow", ReplyAction="http://tempuri.org/IService1/SubmitWorkflowResponse")]
        string SubmitWorkflow(Nsun.Workflow.SerContainer.WFService.SubmitInfo_DTO submitInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNodesByTemplateId", ReplyAction="http://tempuri.org/IService1/GetNodesByTemplateIdResponse")]
        System.Collections.Generic.List<Nsun.Workflow.SerContainer.WFService.InstanceNode_DTO> GetNodesByTemplateId(System.Guid templateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTemplateByIds", ReplyAction="http://tempuri.org/IService1/GetTemplateByIdsResponse")]
        Nsun.Workflow.SerContainer.WFService.NSTemplateInfo GetTemplateByIds(System.Guid templateId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Nsun.Workflow.SerContainer.WFService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Nsun.Workflow.SerContainer.WFService.IService1>, Nsun.Workflow.SerContainer.WFService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string NewTemplate(Nsun.Workflow.SerContainer.WFService.NSTemplateInfo nsTemplateInfo) {
            return base.Channel.NewTemplate(nsTemplateInfo);
        }
        
        public string NewTemplateType(Nsun.Workflow.SerContainer.WFService.NSTemplateType nsTemplateInfo) {
            return base.Channel.NewTemplateType(nsTemplateInfo);
        }
        
        public string DelTemplateTypes(System.Collections.Generic.List<Nsun.Workflow.SerContainer.WFService.NSTemplateType> delItems) {
            return base.Channel.DelTemplateTypes(delItems);
        }
        
        public string NewTemplateTypes(System.Collections.Generic.List<Nsun.Workflow.SerContainer.WFService.NSTemplateType> nsTemplateInfos) {
            return base.Channel.NewTemplateTypes(nsTemplateInfos);
        }
        
        public System.Collections.Generic.List<Nsun.Workflow.SerContainer.WFService.NSTemplateType> GetAllTemplateType() {
            return base.Channel.GetAllTemplateType();
        }
        
        public System.Collections.Generic.List<Nsun.Workflow.SerContainer.WFService.NSTemplateInfo> GetAllTemplateInfoByType(string type) {
            return base.Channel.GetAllTemplateInfoByType(type);
        }
        
        public System.Guid StartWorkflowInfo(Nsun.Workflow.SerContainer.WFService.StartInfo_DTO startInfo, ref string errorInfos) {
            return base.Channel.StartWorkflowInfo(startInfo, ref errorInfos);
        }
        
        public System.Collections.Generic.List<Nsun.Workflow.SerContainer.WFService.NSInstanceInfo> GetNSInfoInfosByTaskId(System.Guid taskId) {
            return base.Channel.GetNSInfoInfosByTaskId(taskId);
        }
        
        public System.Collections.Generic.List<Nsun.Workflow.SerContainer.WFService.NSNodeInfo> GetNSNodeInfosByInstanceId(System.Guid instanceId) {
            return base.Channel.GetNSNodeInfosByInstanceId(instanceId);
        }
        
        public System.Collections.Generic.List<Nsun.Workflow.SerContainer.WFService.NSRoutingData> GetNSRouingData(System.Guid id) {
            return base.Channel.GetNSRouingData(id);
        }
        
        public string SubmitWorkflow(Nsun.Workflow.SerContainer.WFService.SubmitInfo_DTO submitInfo) {
            return base.Channel.SubmitWorkflow(submitInfo);
        }
        
        public System.Collections.Generic.List<Nsun.Workflow.SerContainer.WFService.InstanceNode_DTO> GetNodesByTemplateId(System.Guid templateId) {
            return base.Channel.GetNodesByTemplateId(templateId);
        }
        
        public Nsun.Workflow.SerContainer.WFService.NSTemplateInfo GetTemplateByIds(System.Guid templateId) {
            return base.Channel.GetTemplateByIds(templateId);
        }
    }
}
