#pragma warning disable 1591
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Configuration;
using System.Text;
using NHibernate;
using NHibernate.Cfg;
using CodeSmith.Data.Linq;
using CodeSmith.Data.NHibernate;
using Configuration = NHibernate.Cfg.Configuration;
using Environment = NHibernate.Cfg.Environment;
using Nsun.Domain.DataContent;

namespace Nsun.Domain.DataContent
{
    public partial class DContext : NHibernateDataContext
    {
        #region Session Implementation

        private static object _sessionFactoryLock = new object();

        private static ISessionFactory _sessionFactory = null;

        private ISessionFactory SessionFactory
        {
            get
            {
                lock (_sessionFactoryLock)
                    if (_sessionFactory == null)
                        _sessionFactory = CreateSessionFactory("NsunDB",
                            "Nsun.Domain.DataContent",
                            "NHibernate.Dialect.MsSql2008Dialect",
                            "NHibernate.Driver.SqlClientDriver");

                return _sessionFactory;
            }
        }

        protected override ISession CreateSession()
        {
            return SessionFactory.OpenSession();
        }
        
        protected override IStatelessSession CreateStatelessSession()
        {
            return SessionFactory.OpenStatelessSession();
        }
        
        #endregion
        
        #region Tables
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<Nsun.Domain.DataContent.RoleInfo> _roleInfo;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<Nsun.Domain.DataContent.RoleInfo> RoleInfo
        {
            get
            {
                if (_roleInfo == null)
                    _roleInfo = new Table<Nsun.Domain.DataContent.RoleInfo>(this);
                return _roleInfo;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<Nsun.Domain.DataContent.UserInfo> _userInfo;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<Nsun.Domain.DataContent.UserInfo> UserInfo
        {
            get
            {
                if (_userInfo == null)
                    _userInfo = new Table<Nsun.Domain.DataContent.UserInfo>(this);
                return _userInfo;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<Nsun.Domain.DataContent.UserRelationship> _userRelationship;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<Nsun.Domain.DataContent.UserRelationship> UserRelationship
        {
            get
            {
                if (_userRelationship == null)
                    _userRelationship = new Table<Nsun.Domain.DataContent.UserRelationship>(this);
                return _userRelationship;
            }
        }
        
        #endregion
        
        #region Views
        
        #endregion
        
        #region Functions
        
        #endregion
    }
}

