#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using Nsun.Domain.DataContent;

namespace Nsun.Domain.DataContent
{
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.Diagnostics.DebuggerDisplay("RoleId: {RoleId}")]
    public partial class RoleInfo : EBase
    {
        #region Static Constructor
        
        /// <summary>
        /// Initializes the <see cref="Account"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static RoleInfo()
        {
            AddSharedRules();
        }
        
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Account"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public RoleInfo()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        protected override void Initialize()
        {
            OnCreated();
        }
        
        #endregion
        
        #region Column Mapped Properties
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Int32 _roleId;
        
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.Int32 RoleId
        {
            get { return _roleId; }
            set
            {
                OnRoleIdChanging(value, _roleId);
                SendPropertyChanging("RoleId");
                _roleId = value;
                SendPropertyChanged("RoleId");
                OnRoleIdChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _roleNumber;
        
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String RoleNumber
        {
            get { return _roleNumber; }
            set
            {
                OnRoleNumberChanging(value, _roleNumber);
                SendPropertyChanging("RoleNumber");
                _roleNumber = value;
                SendPropertyChanged("RoleNumber");
                OnRoleNumberChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _roleRemark;
        
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String RoleRemark
        {
            get { return _roleRemark; }
            set
            {
                OnRoleRemarkChanging(value, _roleRemark);
                SendPropertyChanging("RoleRemark");
                _roleRemark = value;
                SendPropertyChanged("RoleRemark");
                OnRoleRemarkChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Int32? _roleType;
        
        [System.Runtime.Serialization.DataMember(Order = 4)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.Int32? RoleType
        {
            get { return _roleType; }
            set
            {
                OnRoleTypeChanging(value, _roleType);
                SendPropertyChanging("RoleType");
                _roleType = value;
                SendPropertyChanged("RoleType");
                OnRoleTypeChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Boolean? _isActive;
        
        [System.Runtime.Serialization.DataMember(Order = 5)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.Boolean? IsActive
        {
            get { return _isActive; }
            set
            {
                OnIsActiveChanging(value, _isActive);
                SendPropertyChanging("IsActive");
                _isActive = value;
                SendPropertyChanged("IsActive");
                OnIsActiveChanged(value);
            }
        }
        
        #endregion
        
        #region Associations Mappings
        
        #endregion
        
        #region Extensibility Method
        
        static partial void AddSharedRules();
        
        partial void OnCreated();
        
        partial void OnRoleIdChanging(System.Int32 newValue, System.Int32 oldValue);
        
        partial void OnRoleIdChanged(System.Int32 value);
        
        partial void OnRoleNumberChanging(System.String newValue, System.String oldValue);
        
        partial void OnRoleNumberChanged(System.String value);
        
        partial void OnRoleRemarkChanging(System.String newValue, System.String oldValue);
        
        partial void OnRoleRemarkChanged(System.String value);
        
        partial void OnRoleTypeChanging(System.Int32? newValue, System.Int32? oldValue);
        
        partial void OnRoleTypeChanged(System.Int32? value);
        
        partial void OnIsActiveChanging(System.Boolean? newValue, System.Boolean? oldValue);
        
        partial void OnIsActiveChanged(System.Boolean? value);
        
        
        #endregion
        
        #region Clone
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual RoleInfo Clone()
        {
            return (RoleInfo)((ICloneable)this).Clone();
        }
        
        #endregion
        
        #region Serialization
        
        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the XML String.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static RoleInfo FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(RoleInfo));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as RoleInfo;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static RoleInfo FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(RoleInfo));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as RoleInfo;
            }
        }
        
        #endregion
    }
}

#pragma warning restore 1591
#pragma warning restore 0414

