#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using Nsun.Domain.DataContent;

namespace Nsun.Domain.DataContent
{
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.Diagnostics.DebuggerDisplay("UserNo: {UserNo}")]
    public partial class UserInfo : EBase
    {
        #region Static Constructor
        
        /// <summary>
        /// Initializes the <see cref="Account"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static UserInfo()
        {
            AddSharedRules();
        }
        
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Account"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public UserInfo()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        protected override void Initialize()
        {
            OnCreated();
        }
        
        #endregion
        
        #region Column Mapped Properties
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _userNo;
        
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String UserNo
        {
            get { return _userNo; }
            set
            {
                OnUserNoChanging(value, _userNo);
                SendPropertyChanging("UserNo");
                _userNo = value;
                SendPropertyChanged("UserNo");
                OnUserNoChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _userName;
        
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String UserName
        {
            get { return _userName; }
            set
            {
                OnUserNameChanging(value, _userName);
                SendPropertyChanging("UserName");
                _userName = value;
                SendPropertyChanged("UserName");
                OnUserNameChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _password;
        
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String Password
        {
            get { return _password; }
            set
            {
                OnPasswordChanging(value, _password);
                SendPropertyChanging("Password");
                _password = value;
                SendPropertyChanged("Password");
                OnPasswordChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Boolean? _gender;
        
        [System.Runtime.Serialization.DataMember(Order = 4)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.Boolean? Gender
        {
            get { return _gender; }
            set
            {
                OnGenderChanging(value, _gender);
                SendPropertyChanging("Gender");
                _gender = value;
                SendPropertyChanged("Gender");
                OnGenderChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Int16? _age;
        
        [System.Runtime.Serialization.DataMember(Order = 5)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.Int16? Age
        {
            get { return _age; }
            set
            {
                OnAgeChanging(value, _age);
                SendPropertyChanging("Age");
                _age = value;
                SendPropertyChanged("Age");
                OnAgeChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _phoneNum;
        
        [System.Runtime.Serialization.DataMember(Order = 6)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String PhoneNum
        {
            get { return _phoneNum; }
            set
            {
                OnPhoneNumChanging(value, _phoneNum);
                SendPropertyChanging("PhoneNum");
                _phoneNum = value;
                SendPropertyChanged("PhoneNum");
                OnPhoneNumChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _address;
        
        [System.Runtime.Serialization.DataMember(Order = 7)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String Address
        {
            get { return _address; }
            set
            {
                OnAddressChanging(value, _address);
                SendPropertyChanging("Address");
                _address = value;
                SendPropertyChanged("Address");
                OnAddressChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _email;
        
        [System.Runtime.Serialization.DataMember(Order = 8)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String Email
        {
            get { return _email; }
            set
            {
                OnEmailChanging(value, _email);
                SendPropertyChanging("Email");
                _email = value;
                SendPropertyChanged("Email");
                OnEmailChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _loginName;
        
        [System.Runtime.Serialization.DataMember(Order = 9)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String LoginName
        {
            get { return _loginName; }
            set
            {
                OnLoginNameChanging(value, _loginName);
                SendPropertyChanging("LoginName");
                _loginName = value;
                SendPropertyChanged("LoginName");
                OnLoginNameChanged(value);
            }
        }
        
        #endregion
        
        #region Associations Mappings
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private IList<UserRelationship> _friendNoUserRelationshipList;
        
        [System.Runtime.Serialization.DataMember(Order = 10, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual IList<UserRelationship> FriendNoUserRelationshipList
        {
            get { return _friendNoUserRelationshipList; }
            set
            {
                OnFriendNoUserRelationshipListChanging(value, _friendNoUserRelationshipList);
                SendPropertyChanging("FriendNoUserRelationshipList");
                _friendNoUserRelationshipList = value;
                SendPropertyChanged("FriendNoUserRelationshipList");
                OnFriendNoUserRelationshipListChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private IList<UserRelationship> _userNoUserRelationshipList;
        
        [System.Runtime.Serialization.DataMember(Order = 11, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual IList<UserRelationship> UserNoUserRelationshipList
        {
            get { return _userNoUserRelationshipList; }
            set
            {
                OnUserNoUserRelationshipListChanging(value, _userNoUserRelationshipList);
                SendPropertyChanging("UserNoUserRelationshipList");
                _userNoUserRelationshipList = value;
                SendPropertyChanged("UserNoUserRelationshipList");
                OnUserNoUserRelationshipListChanged(value);
            }
        }
        
        #endregion
        
        #region Extensibility Method
        
        static partial void AddSharedRules();
        
        partial void OnCreated();
        
        partial void OnUserNoChanging(System.String newValue, System.String oldValue);
        
        partial void OnUserNoChanged(System.String value);
        
        partial void OnUserNameChanging(System.String newValue, System.String oldValue);
        
        partial void OnUserNameChanged(System.String value);
        
        partial void OnPasswordChanging(System.String newValue, System.String oldValue);
        
        partial void OnPasswordChanged(System.String value);
        
        partial void OnGenderChanging(System.Boolean? newValue, System.Boolean? oldValue);
        
        partial void OnGenderChanged(System.Boolean? value);
        
        partial void OnAgeChanging(System.Int16? newValue, System.Int16? oldValue);
        
        partial void OnAgeChanged(System.Int16? value);
        
        partial void OnPhoneNumChanging(System.String newValue, System.String oldValue);
        
        partial void OnPhoneNumChanged(System.String value);
        
        partial void OnAddressChanging(System.String newValue, System.String oldValue);
        
        partial void OnAddressChanged(System.String value);
        
        partial void OnEmailChanging(System.String newValue, System.String oldValue);
        
        partial void OnEmailChanged(System.String value);
        
        partial void OnLoginNameChanging(System.String newValue, System.String oldValue);
        
        partial void OnLoginNameChanged(System.String value);
        
        
        partial void OnFriendNoUserRelationshipListChanging(IList<UserRelationship> newValue, IList<UserRelationship> oldValue);
        
        partial void OnFriendNoUserRelationshipListChanged(IList<UserRelationship> value);
        
        partial void OnUserNoUserRelationshipListChanging(IList<UserRelationship> newValue, IList<UserRelationship> oldValue);
        
        partial void OnUserNoUserRelationshipListChanged(IList<UserRelationship> value);
        
        #endregion
        
        #region Clone
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual UserInfo Clone()
        {
            return (UserInfo)((ICloneable)this).Clone();
        }
        
        #endregion
        
        #region Serialization
        
        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the XML String.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static UserInfo FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(UserInfo));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as UserInfo;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static UserInfo FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(UserInfo));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as UserInfo;
            }
        }
        
        #endregion
    }
}

#pragma warning restore 1591
#pragma warning restore 0414

