#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using Nsun.Domain.DataContent;

namespace Nsun.Domain.DataContent
{
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.Diagnostics.DebuggerDisplay("AutoId: {AutoId}")]
    public partial class UserRelationship : EBase
    {
        #region Static Constructor
        
        /// <summary>
        /// Initializes the <see cref="Account"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static UserRelationship()
        {
            AddSharedRules();
        }
        
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Account"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public UserRelationship()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        protected override void Initialize()
        {
            OnCreated();
        }
        
        #endregion
        
        #region Column Mapped Properties
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Int32 _autoId;
        
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.Int32 AutoId
        {
            get { return _autoId; }
            set
            {
                OnAutoIdChanging(value, _autoId);
                SendPropertyChanging("AutoId");
                _autoId = value;
                SendPropertyChanged("AutoId");
                OnAutoIdChanged(value);
            }
        }
        
        #endregion
        
        #region Associations Mappings
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private UserInfo _friendNoUserInfo;
        
        [System.Runtime.Serialization.DataMember(Order = 2, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual UserInfo FriendNoUserInfo
        {
            get { return _friendNoUserInfo; }
            set
            {
                OnFriendNoUserInfoChanging(value, _friendNoUserInfo);
                SendPropertyChanging("FriendNoUserInfo");
                _friendNoUserInfo = value;
                SendPropertyChanged("FriendNoUserInfo");
                OnFriendNoUserInfoChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private UserInfo _userNoUserInfo;
        
        [System.Runtime.Serialization.DataMember(Order = 3, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual UserInfo UserNoUserInfo
        {
            get { return _userNoUserInfo; }
            set
            {
                OnUserNoUserInfoChanging(value, _userNoUserInfo);
                SendPropertyChanging("UserNoUserInfo");
                _userNoUserInfo = value;
                SendPropertyChanged("UserNoUserInfo");
                OnUserNoUserInfoChanged(value);
            }
        }
        
        #endregion
        
        #region Extensibility Method
        
        static partial void AddSharedRules();
        
        partial void OnCreated();
        
        partial void OnAutoIdChanging(System.Int32 newValue, System.Int32 oldValue);
        
        partial void OnAutoIdChanged(System.Int32 value);
        
        
        partial void OnFriendNoUserInfoChanging(UserInfo newValue, UserInfo oldValue);
        
        partial void OnFriendNoUserInfoChanged(UserInfo value);
        
        partial void OnUserNoUserInfoChanging(UserInfo newValue, UserInfo oldValue);
        
        partial void OnUserNoUserInfoChanged(UserInfo value);
        
        #endregion
        
        #region Clone
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual UserRelationship Clone()
        {
            return (UserRelationship)((ICloneable)this).Clone();
        }
        
        #endregion
        
        #region Serialization
        
        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the XML String.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static UserRelationship FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(UserRelationship));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as UserRelationship;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static UserRelationship FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(UserRelationship));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as UserRelationship;
            }
        }
        
        #endregion
    }
}

#pragma warning restore 1591
#pragma warning restore 0414

